# Generated by Django 4.1.13 on 2024-08-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mymodel_delete_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
